config/routes.rb
Rsp::Application.routes.draw do

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
  resources :navigations
  resources :articles
  resources :uploads

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  
  field :name
  field :content
  field :published_on, :type => Date
  
  belongs_to :navigation
  has_many :uploads
end

app/models/navigation.rb
class Navigation
  include Mongoid::Document
  
  field :name, :type => String
  field :title, :type => String
  field :sort, :type => Integer
  
  has_many :articles
end

app/models/upload.rb
class Upload
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :content_type, :type => String
  field :filename, :type => String
  
  before_create :set_filename, :set_content_type
  after_create :store_file
  after_destroy :delete_file
  
  validates_presence_of :uploaded_file
  
  attr_accessor :uploaded_file
  
  belongs_to :article
  
  def link
    "/data/#{CGI.escape(filename)}"
  end
  
  def src
    file_storage_location
  end
  
  private
  
  def store_file
    File.open(file_storage_location, 'wb') do |f|
      f.write uploaded_file.read
    end
  end
  
  def delete_file
    File.delete(file_storage_location)
  end
  
  def file_storage_location
    File.join(Rails.root, 'public', 'data', filename)
  end
  
  def set_filename
    self.filename = random_prefix + '_' + uploaded_file.original_filename
  end
  
  def set_content_type
    self.content_type = uploaded_file.content_type
  end
  
  def random_prefix
    Digest::SHA1.hexdigest(Time.now.to_s.split(//).sort_by {rand}.join)
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :setup_navigation
  
  private
    def setup_navigation
      
      @navigations = Navigation.asc("sort", "name")
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @articles = Article.where(:navigation_id => nil)
  end
end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  # GET /navigations
  # GET /navigations.json
  def index
    @navigations = Navigation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @navigations }
    end
  end

  # GET /navigations/1
  # GET /navigations/1.json
  def show
    @navigation = Navigation.find(params[:id])
    flash.now[:notice] = "no articles for this navigation" if @navigation.articles.size == 0

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/new
  # GET /navigations/new.json
  def new
    @navigation = Navigation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/1/edit
  def edit
    @navigation = Navigation.find(params[:id])
  end

  # POST /navigations
  # POST /navigations.json
  def create
    @navigation = Navigation.new(params[:navigation])

    respond_to do |format|
      if @navigation.save
        format.html { redirect_to @navigation, notice: 'Navigation was successfully created.' }
        format.json { render json: @navigation, status: :created, location: @navigation }
      else
        format.html { render action: "new" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /navigations/1
  # PUT /navigations/1.json
  def update
    @navigation = Navigation.find(params[:id])

    respond_to do |format|
      if @navigation.update_attributes(params[:navigation])
        format.html { redirect_to @navigation, notice: 'Navigation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navigations/1
  # DELETE /navigations/1.json
  def destroy
    @navigation = Navigation.find(params[:id])
    @navigation.destroy

    respond_to do |format|
      format.html { redirect_to navigations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @upload = Upload.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end
  
  def new
    @upload = Upload.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end
  
  def show
    @upload = Upload.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
  def create
    @upload = Upload.new(params[:upload])
    
    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: "File has been uploaded successfully" }
        format.json { render json: @upload, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigations_helper.rb
module NavigationsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<h4>
  <small>
    <%= article.published_on %>
    <%= link_to 'edit', edit_article_path(article) if user_signed_in? %>
  </small><br />
  <%= article.name %>
</h4>
<p>
  <%= article.content %>
</p>
<%= render :partial => "uploads/image", :collection => article.uploads %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :navigation %><br />
    <%= collection_select(:article, :navigation_id, Navigation.all, :id, :name, {:include_blank => true}) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.name %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @article.name %>
</p>
<p>
  <b>Published:</b>
  <%= @article.published_on %>
</p>
<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<%= render :partial => "articles/article", :collection => @articles  %>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MySpecialThing.com</title>
    <meta name="description" content="MySpecialThing.com - Kreationen f&uuml;r das Spezielle">
    <meta name="author" content="Isabel Imper">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller] %>">
    <div id="container" class="container">
      <header>
        <nav>
          <ul class="hmenu">
            <%= render 'shared/navigation' %>
          </ul>
        </nav>
        <nav>
          <ul class="vmenu">
            <li <%= "id='active' class='active'" if current_page? :action => 'index', :controller => '/home' %>>
              <%= link_to_unless_current "Home", { :action => 'index', :controller => '/home' } %>
            </li>
            <% @navigations.each do |navigation| %>
              <li <%= "id='active' class='active'" if navigation.id.to_s === params[:id] %>>
                <%= link_to_unless_current navigation.name, navigation %>
              </li>
            <% end %>
          </ul>
        </nav>
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "#{name}" if msg.is_a?(String) %>
        <%- end -%>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/navigations/_form.html.erb
<%= form_for(@navigation) do |f| %>
  <% if @navigation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@navigation.errors.count, "error") %> prohibited this navigation from being saved:</h2>

      <ul>
      <% @navigation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sort %><br />
    <%= f.number_field :sort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/navigations/edit.html.erb
<h1>Editing navigation</h1>

<%= render 'form' %>

<%= link_to 'Show', @navigation %> |
<%= link_to 'Back', navigations_path %>

app/views/navigations/index.html.erb
<h1>Listing navigations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Sort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @navigations.each do |navigation| %>
  <tr>
    <td><%= navigation.name %></td>
    <td><%= navigation.title %></td>
    <td><%= navigation.sort %></td>
    <td><%= link_to 'Show', navigation %></td>
    <td><%= link_to 'Edit', edit_navigation_path(navigation) %></td>
    <td><%= link_to 'Destroy', navigation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Navigation', new_navigation_path %>

app/views/navigations/new.html.erb
<h1>New navigation</h1>

<%= render 'form' %>

<%= link_to 'Back', navigations_path %>

app/views/navigations/show.html.erb
<%= render :partial => "articles/article", :collection => @navigation.articles %>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'New Navigation', new_navigation_path %></li>
  <li><%= link_to 'List Navigations', navigations_path %></li>
  <li><%= link_to 'New Article', new_article_path %></li>
  <li><%= link_to 'List Articles', articles_path %></li>
  <li><%= link_to 'New Image', new_upload_path %></li>
  <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/uploads/_form.html.erb
<%= form_for(@upload, :multipart => true) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :article %><br />
    <%= collection_select(:upload, :article_id, Article.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :uploaded_file %>
  </div>
  <div class="actions">
    <%= f.submit "Upload", :disable_with => 'Uploading...' %>
  </div>
<% end %>

app/views/uploads/_image.html.erb
<%= image_tag image.link, :alt => image.name %>

app/views/uploads/index.html.erb
<%= render 'form' %>

app/views/uploads/new.html.erb
<%= render 'form' %>

app/views/uploads/show.html.erb
<h4><%= @upload.name %></h4>
<%= image_tag @upload.link, :alt => @upload.name %>
<p>
  <strong>Description:</strong> <%= @upload.description %><br>
  <strong>src:</strong> <%= @upload.src %>
</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>